# Generated by Django 3.0.4 on 2021-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
