# Generated by Django 3.0.4 on 2021-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerAPI', '0002_auto_20210327_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
